### ISSUE TITLE
Configuration of LDAP

### ISSUE THREAD

**Issue by roversmanoj** [CognizantOneDevOps/Insights#1]
hi Team,

I have installed all the tools required for Insight, and able to view the login page of insight app. I was not able to login as it requires an admin credentials. Is there any default admin credentials to login? or point me on how to configure ldap credential?

kindly help me to resolve this issue.

Regards,
Manoj.

**Comment by vganjare** [comment]
Hi Manoj,

I hope you have configured server-config.json as mentioned @ https://onedevops.atlassian.net/wiki/spaces/OI/pages/211638/Installation+of+InSights 

Set following attribute:
  "disableAuth": false,
  "enableNativeUsers": true,

Using this setting, you should be able to login using the users created in Grafana. Default Grafana user is admin/admin

Thanks,
Vishal

**Comment by roversmanoj** [comment]
hi Vishal,

Thanks for the reply. I tried the above steps, adding below properties in server-config.json file. 
"disableAuth": false,
"enableNativeUsers": true,

But still I was not able to login with insight portal. I was able to login Grafana portal using admin/admin . I have attached server-config.json file and the error am getting while logging in.
![insighterror](https://user-images.githubusercontent.com/8178256/33121487-e7b4188e-cf9a-11e7-82fd-cb0c564f2d3c.png)
[server-config.txt](https://github.com/CognizantOneDevOps/Insights/files/1495498/server-config.txt)

**Comment by vganjare** [comment]
Hi Manoj,

Is the PlatformService running? Can you check if tomcat logs directory has PlatformService directory? Also, please share the tomcat logs and PlatformService logs.

Thanks,
Vishal

**Comment by roversmanoj** [comment]
hi Vishal,

Thanks for the quick response.I found Platformservice was not running, due to some ssl errors. i fixed it and able to login insight url. I configured ES and neo4j in Grafana as well.  Under tools configuration, i configured jenkins as shown. But while creating dashboard in grafana, i found no build values were found in datasource, so the chart remains with empty values. Could you please help me to understand, how to render charts with jenkins data??

![image](https://user-images.githubusercontent.com/8178256/33196081-1c09c87c-d103-11e7-83d3-2e6cca1cf6a3.png)
![image](https://user-images.githubusercontent.com/8178256/33196130-848c0d38-d103-11e7-9b0e-2d315b152587.png)
![image](https://user-images.githubusercontent.com/8178256/33196144-aa3474da-d103-11e7-9e91-d613906beefd.png)


Thanks,
Manoj.

**Comment by vganjare** [comment]
Hi Manoj,

Can you try updating the config.json in PlatformAgents? Following are the steps to configure GitAgent:
1. Update the config.json located at https://github.com/CognizantOneDevOps/Insights/tree/master/PlatformAgents/com/cognizant/devops/platformagents/agents/scm/git
2. Run command python from https://github.com/CognizantOneDevOps/Insights/tree/master/PlatformAgents
3. In python console, fire: from com.cognizant.devops.platformagents.agents.scm.git.GitAgent import GitAgent
4. GitAgent()
Similarly, you can configure other agents.

Thanks,
Vishal

**Comment by roversmanoj** [comment]
Hi Vishal,

Thanks for the reply. Am closing this issue, as my ldap issue was resolved. Regarding this data collection , i will open a new issue. 


Regards,
Manoj.
