### ISSUE TITLE
Running Insights Inference - Spark Jobs Issue

### ISSUE THREAD

**Issue by SwethaSridhar** [CognizantOneDevOps/Insights#10]
Hi,
For running the Insights Inference-Spark Jobs, it is given that the jar "PlatformInsights-0.0.1-SNAPSHOT-jar-with-dependencies.jar" has to be run. But, the path in which the Spark Jar could be manually installed, "%WORKSPACE%\Insights\PlatformInsights" doesn't exist.Please help me to resolve this issue.
Regards,
Swetha.

**Comment by AkshaySharma7** [comment]
Hi Swetha,

Thank you for reaching us. "**%WORKSPACE%**" would be the directory, where Insights is cloned. Request you to please refer the instructions given at https://onedevops.atlassian.net/wiki/spaces/OI/pages/81855063/Running+InSights+Inference+-+Spark+Jobs to run Insights Inference-Spark jobs. Also, you could download the .jar file from the same page.

Regards,
Akshay

**Comment by rajkumarc2000** [comment]
Please note spark is needed only for the Insights tab and for normal dashboards you will not need Spark related configurations. Closing this issue based on the above answer.
