### ISSUE TITLE
SSL Verify option not available via the UI

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#104]
The sslverify option is not showing up via the UI. Addition of the ssl verify option via the config.json file gets overridden every time the agent is opened via the edit option in the "Agent Management" section.

Subsequent agent start does not work with an SSL exception.

![image](https://user-images.githubusercontent.com/40206308/41855097-6ca991d2-78af-11e8-936e-e82684e0e5d2.png)

**Comment by SashikalaV** [comment]
Can you try the below change in the file BaseAgent.py in the path: PlatformAgents/com/cognizant/devops/platformagents/core/

Current line # 127: sslVerify = config.get('sslVerify', True)
To be modified to:  sslVerify = config.get('sslVerify', False)

**Comment by gjerin594** [comment]
We have changed the value in our python script from sslVerify = true to false. The agent health scan has progressed. However, the UI seems to be throwing an error of a file not being found. Since, during configuration we are not asked to mention any file paths or such details, the root cause of the issue remains unclear.

![image](https://user-images.githubusercontent.com/40206308/42031175-eebe17b6-7af2-11e8-9fa1-6a90b8288ee3.png)


![image](https://user-images.githubusercontent.com/40206308/42031164-e5d7ca20-7af2-11e8-879c-0a93837e8ace.png)

**Comment by SashikalaV** [comment]
Please try the following steps:
1. Agent to be stopped in the  UI
2. Edit the config.json file within the GIT Agent folder 
3. Add the following as new line @ Line # 60: "sslVerify" : false, 
4. Start the service of the BitBucket Agent

**Comment by gjerin594** [comment]
@SashikalaV  We could see that in addition to the sslVerify variable there are a few request.get() functions in the respective Agent scripts. Would it be possible to incorporate some fixes such that the sslVerify option is available via the UI, such that it takes care of all such REST calls?

**Comment by vishwajitmankar** [comment]
It should be available in next release. Currently it is work in progress.

**Comment by vishwajitmankar** [comment]
Please test it with latest v4.3. You need not update other components, just update your agent to v4.3 though agent management UI. Please take back-up of your config.json as well as tracking.json

**Comment by gjerin594** [comment]
@vishwajitmankar Thank you for the support. Issues resolved.
