### ISSUE TITLE
Unable to configure Artifactory Agent from the UI

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#107]
Environment:
1. Insights Version - 4.1 / Platform Service binary created from latest master code.
2. OS - RHEL 7.5
3. All services and tools up and runnning
4. Registration of agents - Online
4. Bitbucket Agent configured via UI.

Issue:

After selecting the Artifactory option from the drop down in the "Agent Management" tab, we are able to see an "artifactory" folder get created in the unzip path mentioned in the server-config.json file. 
However, as soon as the register option is invoked, the service fails to get registered.

We could also observe that the "artifactory" folder is not getting created in the "PlatformAgents" path, where a folder presently exists for the bitbucket agent configured via the UI.

![image](https://user-images.githubusercontent.com/40206308/42031419-d85e3360-7af3-11e8-82c2-01a1fc5d5956.png)

**Comment by nisanthjs** [comment]
At the time of the agent configuration via UI, we could see the below error in the PlatformService log file. We have  attached the same for your reference. Is this a known issue? Please advise.
[platformservice_artifactory.log](https://github.com/CognizantOneDevOps/Insights/files/2145078/platformservice_artifactory.log)

**Comment by gjerin594** [comment]
Issue solved. The problem was with the unzip path. Corrections in the server-config.json fixed it.
