### ISSUE TITLE
SSL Verification error for Jenkins Agent

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#111]
We have configured a Jenkins agent via the Insights UI (v4.1). The agent is unable to read the data due to an SSL verification error.

The UI did not have an option to pass the username and the password. We hard coded the credentials in the python script for the rest facade. This took care of the authentication failure error.

Presently, even after giving sslVerify = False in the BaseAgent.py and also setting the (verify = False) for all the requests.get() methods, we are facing the ssl verification failure issue. 

Please help in getting it resolved.

OS - RHEL 7.5
Python: 2.7.5
Insights Version: 4.1
Jenkins Agent version: 4.1

![image](https://user-images.githubusercontent.com/40206308/42760389-fe84b9be-8927-11e8-97d5-9bd1fb97b707.png)

**Comment by SashikalaV** [comment]
pls try "sslVerify = false" instead of "sslVerify = FALSE"

**Comment by gjerin594** [comment]
The issue was solved as mentioned below.

Along with the sslVerify variable, there are many requests.get() commands in Jenkins agent script. If you don't want the verification, please add verify=False to the commands.

**Comment by gjerin594** [comment]
The issue was solved as mentioned below.

Along with the sslVerify variable, there are many requests.get() commands in Jenkins agent script. If you don't want the verification, please add verify=False to the commands.
