### ISSUE TITLE
Change of Default Credentials

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#113]
How can we remove / change the default admin / admin credentials for the InSights UI application?

From what i have understood, the credentials being used are the ones from the Postgres DB for Grafana. How can i add another set of credentials for the same? Could you please share the query or the script to be run on the postgres DB?

**Comment by vishwajitmankar** [comment]
You cannot remove Admin user, however, should be able to change password by logging in directly in Grafana

**Comment by vishwajitmankar** [comment]
Closing this issue.
