### ISSUE TITLE
Error while running PlatformInsights-0.0.1-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by techieatheart** [CognizantOneDevOps/Insights#122]
To run PlatformInsights jar for Insights Inference, getting an error stating `ERROR ErrorLogger: Job (iSightSpark.SparkJobExecutorModule threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid resource given; expecting [index]/[type] - received ]`

Please help by giving a resolution to this exception.
![platforminsightserror](https://user-images.githubusercontent.com/6586463/43567887-c4861204-9650-11e8-902a-f77bdc1a6d0d.JPG)

**Comment by vishwajitmankar** [comment]
Do you have server-config.json in classpath with sparkConfiguration section having all correct details..

**Comment by singhsid0401** [comment]
Please validate my current understanding of the setup:-
1) **Application Server**
2) **DB Server**
3) **Spark**(Inference Server) which will contain modified **server-config.json** in $INSIGHTS_HOME.
Now, inside server-config.json's sparkConfigurations section, **sparkElasticSearchHost** will have the ip of DB Server as its value and **sparkMasterExecutionEndPoint** will have ip of Spark Server as its value. Is this correct?

**Comment by vishwajitmankar** [comment]
Try below configuration.  
"sparkConfigurations": {
    "appName" : "inSights",
	"master" : "local[*]",
	"sparkExecutorMemory" : "8g",
	"sparkElasticSearchHost": "http://<ElasticSearch DB IO>",
	"sparkElasticSearchPort": "9200",
	"sparkElasticSearchConfigIndex": "spark-jobs-conf/configs",
	"sparkElasticSearchResultIndex": "spark-jobs-conf/kpiresults",
	"kpiSize": "30"
  }

Hope you have uploaded KPI definition as given on confluence using curl command. You will need to frame the query as given in sample KPI. Please read lucence query language at Elasticsearch documentation.

**Comment by singhsid0401** [comment]
- After making the above changes in server-config.json and pushing a couple of KPIs in ElasticSearch, ran **PlatformInsights-0.0.1-SNAPSHOT-jar-with-dependencies.jar** as a service. This time it is running without giving errors. It makes a log file called **platforminsights.log** which reads the following on loop: 

`2018-08-08 22:46:29 DEBUG SparkJobExecutor:56 - Starting Spark Jobs Execution
2018-08-08 22:46:29 DEBUG SparkJobConfigHandler:47 - Loading jobs from Elasticsearch
` 

- After this also, the Inference UI tab named 'InSights' is not reflecting any metric. I suspect it has got something to do with some of the KPI definition values being put.

There are still some doubts even after seeing the documentation. Can you please clarify the use of following keys in KPI definitions: 
1. schedule - Difference between 'schedule' inside 'kpiDefinition' and outside of it, while adding KPI?
2. nextRun - ?
3. lastRunTime - ?

- Lastly, could you tell the significance of writing 21600 at the end of `java -jar PlatformInsights-0.0.1-SNAPSHOT-jar-with-dependencies.jar 21600` ?

**Comment by singhsid0401** [comment]
Any help on the above comment? Stuck at it for days..

**Comment by vishwajitmankar** [comment]
Below link has each field description - 
https://onedevops.atlassian.net/wiki/spaces/OI/pages/81756368/InSights+Inference+-+KPI+Job+Configuration

You need to check whether Elasticsearch has any data. Did you agents run and you have data in Neo4j DB as well as Elasticsearch? You can also check that by running query present inside your KPI definition. 
Please note the sample give in documentation is for example purpose only. Your field names might differ from what is given in sample. For example, you might not have SPKvector, SPKtoolName, SPKstatus etc in your DB. Replace them with relevant field names from your Elasticsearch DB.
