### ISSUE TITLE
Not able to Render Graph in Grafana

### ISSUE THREAD

**Issue by SwethaSridhar** [CognizantOneDevOps/Insights#13]
Hi,
While trying to configure sonar tool, Neo4j is found to get the sonar data as follows
![image](https://user-images.githubusercontent.com/22519028/33599734-077ca60e-d9cd-11e7-8cec-448fe1c9b940.png)
And, in RabbitMQ, under the Queue CODEQUALITY_SONAR_DATA, we get the following
![image](https://user-images.githubusercontent.com/22519028/33600851-867bbd02-d9d0-11e7-94f4-e7601d353a71.png)
For rendering the graph in grafana for the same sonar data,we used the query from the neo4j as follows
![image](https://user-images.githubusercontent.com/22519028/33601357-fe22a496-d9d1-11e7-836a-4c406f0a88e1.png)
But, we get some error as
![image](https://user-images.githubusercontent.com/22519028/33601411-24b7a264-d9d2-11e7-8409-88c4c188cab8.png)
It would be better if we are provided with a clear picture in rendering the graph and also with the queries that needs to be used, to get the data from neo4j.
Regards,
Swetha

**Comment by vganjare** [comment]
Hi Swetha,

Try the queries directly in Neo4j browser. If the query is correct, then only use it in grafana.

Thanks,
Vishal
