### ISSUE TITLE
Insights DataSource - Failover/Backup Startegy

### ISSUE THREAD

**Issue by nisanthjs** [CognizantOneDevOps/Insights#140]
Hi Team,

We are currently using Insights 4.2 and we are trying to come up with a backup or failover (if need be) instance for our datasources - Neo4j and Elastic Search. 
We do see an option to backup data for Elastic Search & Neo4j from the documentation, but in our case we are looking for an instance that we can switch to in case our existing datasource is impacted. 
Please let us know if you have any suggestion for the same. 
Can we achieve this by just backing up the data directory (NEO4J_HOME/neo4j-community-3.3.0/data/) for Neo4j and the Index directory (/var/lib/elasticsearch/) for elastic search. 
Please share your thoughts regarding the same.

**Comment by nisanthjs** [comment]
Hi Team,
        Do you have any suggestion for the requirement?

**Comment by vishwajitmankar** [comment]
Insights backup option periodically takes back in json format, which then needs to be manually uploaded in case of an emergency. Data purging option in latest release periodically deletes old data if kept ON. Both options needs to be run carefully. 
As another strategy  backing up "data" folder periodically is another best option.

**Comment by vishwajitmankar** [comment]
Closing this issue as there are no more comments.
