### ISSUE TITLE
Purge duplicate data from the DBs

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#142]
Does the Insights architecture have a purging mechanism to take care of data duplication? 

Also is there a targeting mechanism we can you during purging to get rid of specific indices / data from both Neo4j and Elastic Search?

**Comment by gjerin594** [comment]
Does InSights have any specific APIs for data purging from the DBs? For example, I want to remove all the data for Jenkins alone. Does the present setup support such a requirement? If so is it by means of an API in InSights or is it by means of a query in Neo4j? Could you help with a sample query for the same?

**Comment by gjerin594** [comment]
@vishwajitmankar If i were to delete the node for Jenkins from Neo4j, would the deletion of data get reflected in the ES DB? Also would the node be recreated when the data is getting posted into Neo4j?

**Comment by vishwajitmankar** [comment]
Yes, it will. You can test it yourselves, by create/update/delete in neo4j. Please read more about Graphaware plugin.
