### ISSUE TITLE
Data is not getting posted to the Elastic Search DB. 

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#146]
Problem statement:
1. All agents running and collecting data.
2. Neo4j, Rabbitmq and ES DB up and running.
3. Data collected is not getting posted from the Neo4j DB via the graphaware plugin to ES.

Log file for Neo4j log attached.
[Error.log.txt](https://github.com/CognizantOneDevOps/Insights/files/2351570/Error.log.txt)

**Comment by gjerin594** [comment]
A restart of Neo4j managed to fix the issue and send the data to the ES DB. However, we have missed the data for the time period over which the above mentioned error occurred. Could you let us know how this issue of missing data can be tackled? Also could you give an idea so as to why the service failed in the first place on the basis of the logs?

**Comment by gjerin594** [comment]
@vishwajitmankar  We are getting very frequent errors with the bulk data push from Neo4j to elastic search. Could you kindly advise on the steps that can be taken to avoid such a situation?

[errorlog.txt.txt](https://github.com/CognizantOneDevOps/Insights/files/2366385/errorlog.txt.txt)

**Comment by vishwajitmankar** [comment]
You can put restriction on number of nodes to be copied Graphaware plugin settings in neo4j conf file.
