### ISSUE TITLE
The download scripts cannot be found on Github.

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#148]
The download scripts for Insights were not available at https://github.com/CognizantOneDevOps/Insights/blob/master/Deployment/RHEL7/ 

The URL was returning a 404 ERROR. Could you please look into it? Thanks in advance! :+1:

**Comment by gjerin594** [comment]
@vishwajitmankar The link was taken from https://onedevops.atlassian.net/wiki/spaces/OI/pages/450592772/Linux+Installation

**Comment by gjerin594** [comment]
@vishwajitmankar Could you please point out the use of the refreshTime tag in the server-config.json file?

**Comment by vishwajitmankar** [comment]
You can ignore that parameter. We are not using it anymore as product is open source.
