### ISSUE TITLE
Data getting queued in rabbitmq without subsequent push to the persistence tier for the Rally Agent

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#168]
@vishwajitmankar 
The data from Insights for the Rally Agent is having issues at the moment. The data that is getting pushed from the agent is queuing up at Rabbitmq. However, the subsequent push to the DBs via the Engine is not happening. We are able to see that many messages are waiting for acknowledgement from the server side. Once we stop the agent from pushing data, we can see that over time the data is getting pushed to the DBs. One of the main issues we have been facing is that the size of the queued up messages goes up drastically and we miss a lot of data. Also, after a while there are no consumers found for Rally in Rabbitmq and the insights engine logs have a connection reset by peer error.

![image](https://user-images.githubusercontent.com/40206308/46665014-34939480-cbe0-11e8-94f8-c1c5d600a30b.png)

As you can see from the screenshot, the messages are getting queued up. This was not observed on any of the other agents. Please advice on how this can be tackled for Rally? Thanks in advance.

**Comment by gjerin594** [comment]
@vishwajitmankar - The issue with rally is still seen to persist. I have added a two minute wait in the agent code as well. However, the issue is still seen to persist. Would you have any suggestions from where i could debug and make changes to counter this issue? After the number of queued messages reaches a high number, I can see that the consumer is getting deleted and the messages are not getting sent. On restarting the engine jar, I was able to see the consumer getting added. But it hits a disk write error very fast and the system stops taking data from the message queue. Any help on this issue would be much appreciated.Thanks in advance.

**Comment by vishwajitmankar** [comment]
Add 'dataFetchCount' field in your RallyAgent's config.json and keep value as 100 and also use latest 4.5 engine which has 'prefetchCount' field which you need to add in server-config.json. This defines how much packets engine should consume at a time. Default value is 10. Try to come to a optimal number as per your load for both 'dataFetchCount' and 'prefetchCount' This should control huge follow of data between agent-RabbitMQ-Engine.

**Comment by gjerin594** [comment]
Could you please explain the function and the location for adding the dataFetchCount variable? @vishwajitmankar Thanks in advance.

**Comment by vishwajitmankar** [comment]
dataFetchCount basically breaks data into chunk of 100/500/1000 whatever you set. That way engine has only those many nodes to to create at a time. Otherwise, whatever number of data your agent pulls (which can be huge sometime based on tool) will go in on MQ packet. Basically you are breaking huge data in smaller packets to reduce load on engine. preFetchCount on engine side, works on limited packets at a time. 
For example, if you have 10000 nodes being pulled by agent from tool, agent will break it into 100 packets and engine will consume say 10 packages at a time, meaning 1000 nodes. This will reduce load on engine and make data flow smooth.

**Comment by gjerin594** [comment]
Hi @vishwajitmankar - I have replaced the engine jar / platform service war and the app folder as per https://onedevops.atlassian.net/wiki/spaces/OI/pages/491388976/Upgrade+Grafana+on+Linux.


After making these changes and adding the prefetchCount variable to the server-config.json, I am facing the following issues:

1. Prefetch count in Rabbitmq is still 10.
![image](https://user-images.githubusercontent.com/40206308/46997646-d9acf080-d13d-11e8-8473-f10889cc1942.png)


2. The platform service is now unable to authenticate / get the logo etc. This was seen from the logs. I have given the same credentials that i am using for Grafana on the same machine in the server-config.json.
![image](https://user-images.githubusercontent.com/40206308/46997676-ecbfc080-d13d-11e8-98c2-deb12dcc7dc0.png)

3. Could you also please mention the use of the "username" and "passwd" fields in the server-config.json? I have presently added the creds for tomcat there. PFA a copy of the server-config.json file i am using.

[server-config.zip](https://github.com/CognizantOneDevOps/Insights/files/2481768/server-config.zip)

Thanks in advance. Really appreciate the prompt support.

**Comment by gjerin594** [comment]
@vishwajitmankar - Is there any difference in the way the InsightsTimeX field is processed from version 4.5 onwards? After adding the new engine jar and platform service, i noticed an error in neo4j.

2018-10-16 09:37:58.929+0000 WARN  Failed to execute an action against Elasticsearch. Details: {"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [inSightsTimeX]"}],"type":"mapper_parsing_exception","reason":"failed to parse [inSightsTimeX]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"2018/10/16 09:28 AM\" is malformed at \"/10/16 09:28 AM\""}}

**Comment by gjerin594** [comment]
@vishwajitmankar Will the rally agent code also have to be updated to 4.5 for the changes to take effect?

**Comment by vishwajitmankar** [comment]
Yes you can upgrade to 4.5 version. Tomcat issue shouldn't arise as there are no changes in terms of Grafana connectivity. The date format issue should go away in next release (Fix already present in master). However, it should not create any data replication issue as such.
