### ISSUE TITLE
Collecting data from Elastic Search to grafana

### ISSUE THREAD

**Issue by roversmanoj** [CognizantOneDevOps/Insights#18]
Hi,
We are able to collect the data from neo4j and render the graph in grafana.
But, we want some information on fetching the data from Elastic Search datasource.
- The Spark Job jar is configured and is running.
- PlatformEngine.jar is running too and data is added to the RabbitMQ Queue.
But,we are not sure if data is indexed in Elastic Search.
Please give a clear picture on how to validate the data in ES,how to render the graph in grafana,the graphs that supports ES and also about the queries that needs to be used in the graph.
Regards,
Manoj

**Comment by rajkumarc2000** [comment]
Please note data is indexed to ES directly from neo4j using Graphaware plugin which is installed along with Neo4j. There is no separate process for ES induction. In terms of what panels are supported for ES and what are supported for Neo4j - please refer to issue #13 and also the below documentation https://onedevops.atlassian.net/wiki/spaces/OI/pages/220935/Dashboard+configurations+for+InSights
