### ISSUE TITLE
Unable to register agent via UI

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#187]
After installation of insights, i try to register an agent from the UI. But the registration fails with a message "Agent register fail". 

The version of insights installed is the latest one and the artifacts are taken from https://platform.cogdevops.com/insights_install/installationScripts/latest/RHEL/artifacts/ as per the installation scripts.

All the other components are up and running. There is seen to be an issue with the Platform Engine from the logs. PFA a copy of the logs. 

Also, from RabbitMQ it can be seen that the agent queues have no consumers.

Please help rectify the issue. Thanks in advance. @vishwajitmankar 

[EngineLog.txt](https://github.com/CognizantOneDevOps/Insights/files/2632933/EngineLog.txt)
![image](https://user-images.githubusercontent.com/40206308/49284888-ea31e400-f4bb-11e8-94c1-304e01a6dbab.png)

**Comment by vishwajitmankar** [comment]
All component artifacts should be taken from http://platform.cogdevops.com/insights_install/release/latest/
Also please check tomcat logs for registration failure issue. If you are on latest release then logs will be at $INSIGHTS_HOME/logs folder.

**Comment by vishwajitmankar** [comment]
Also could you please point out, which document page referring to https://platform.cogdevops.com/insights_install/installationScripts/latest/RHEL/artifacts/  for components.

**Comment by gjerin594** [comment]
Hi @vishwajitmankar - PFA a copy of the error log from Tomcat. The path I got was from one of the older installation scripts. I have made the due changes in the components. But the issue is still seen to persist.
[TomcatErrorSnippet.txt](https://github.com/CognizantOneDevOps/Insights/files/2643368/TomcatErrorSnippet.txt)

**Comment by gjerin594** [comment]
From the logs i was able to see that a null value is being inserted into "unique_key" column and this throws a constraint violation. Would this be able to shed more light on where the issue has occurred?

**Comment by vishwajitmankar** [comment]
We have deprecated unique_key column (remove NOT NULL constraint). You will need to clear agent_configuration table after taking back up. Deploy new PlatforService.WAR (This should update agent_configuration and remove NOT NULL constraint on unique_key column. If not please remove it manually through DB command) and re-register agent again.

**Comment by gjerin594** [comment]
Thank you. Where is the agent configuration table present in the postgres db?  Also, if I were to install a fresh instance with the new scripts in github will the issue be solved? I'm guessing the changes are there in the new sql scripts that are executed during the set up of tables in postgres?

**Comment by vishwajitmankar** [comment]
Yes. Fresh installation should not face this issue.

**Comment by gjerin594** [comment]
Just completed the fresh  installation. Agent registrations are back. Thanks a lot @vishwajitmankar . Could you please mention how i can access the agent configuration table present on the postgres db to update / recreate the table without the "NOT NULL" constraint? I needed to resolve the issue on my older systems after update.

Questions:
1. User - Do i use the postgres user or the grafana user?
2. Which data base / schema in postgres is the agent configuration table  present inside?
