### ISSUE TITLE
Unable to Schedule Agent to run at the same time everyday

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#198]
I have presently set the runSchedule field in the config.json for my agent to 1440 to make it run at an interval of 24 hours. However, the agent is not getting restarted at the same time on a daily basis. Is the time for restarting the agent measured from the time it starts the data collection or does runSchedule refer to the time after the collection is complete?

**Comment by gjerin594** [comment]
@vishwajitmankar - Could you provide your inputs on the same?

**Comment by vishwajitmankar** [comment]
It would be every 24 Hrs from first start.
