### ISSUE TITLE
RHEL Deployments

### ISSUE THREAD

**Issue by vaibhavdevops** [CognizantOneDevOps/Insights#23]
Team,
I am trying to install Insights on RHEL7,  and I referred to https://onedevops.atlassian.net/wiki/spaces/OI/pages/211638/Installation+of+InSights for the instruction. The recommendation is to use 2 machines, but there is no clarity below points:

1) What all packages should be installed on machine1 and machine 2
2) What setting to change in each server to make the integration possible

Thanks
Vaibhav

**Comment by rajkumarc2000** [comment]
Hi Vaibhav, 

If you drill down into the section of Network ports - there are details present on what should be present on machine 1 and what should be present on machine 2. And also under the Installation instructions under Linux section - there is a small recommendation on how data store should be kept on one machine and the other components in the other. 

With the above being said - we will take this as a feedback and provide these information/instructions in the hardware requirements section as well. 

Thanks
Rajkumar

**Comment by vaibhavdevops** [comment]
Hi Raj,
I tried to do deployment for Insight today on RHEL7 servers on VMs available in my companies internal cloud infrastructure. @vganjare , helped me to debug theses issues as well. Finally found the issues, mainly related to files permission. Is there a way to share these finding on confluence, so that other people trying these deployments can be benefited with those? We are still facing some issues, which yet to be resolved. but i am hopeful that we can those resolved soon.

Thanks for bunch @vganjare for helping over the weekend

Thanks
Vaibhav

**Comment by rajkumarc2000** [comment]
Sure Vaibhav - Currently Anonymous contribution is not allowed on Confluence pages for obvious reasons. I will add your ID to the list of folks who can contribute to the confluence page and also provide direct link to the Troubleshooting link on the confluence -> https://onedevops.atlassian.net/wiki/spaces/OI/pages/41418753/Troubleshooting

We can add the installation issues as a sub section there. 

@mayankdevops - can you please add Vaibhav official email ID to the list of users who can edit the confluence pages

Regards
Rajkumar

**Comment by mayankdevops** [comment]
Hello Vaibhav,

We have added you to our confluence group. You should see an invitation email for the same. Please let us know if any issues.

Thanks,
-Mayank Gangwal

**Comment by rajkumarc2000** [comment]
Closing this issue since the deployments have been completed successfully.
