### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.apache.poi:poi

### ISSUE THREAD

**Issue by Bing-ok** [CognizantOneDevOps/Insights#262]
## Issue description:
There are multiple versions of **_org.apache.poi:poi_** in **_PlatformRegressionTest_**. As shown in the following dependency tree, according to Maven's "nearest wins" strategy, only **_org.apache.poi:poi:4.1.2_** can be loaded, **_org.apache.poi:poi:4.1.0_** will be shadowed.

However, several methods defined in shadowed version **_org.apache.poi:poi:4.1.0_** are referenced by client project via **_org.apache.poi:poi-ooxml:4.1.0_** but missing in the actually loaded version **_org.apache.poi:poi:4.1.2_**.

For instance, the following missing method(defined in **_org.apache.poi:poi:4.1.0_**) are actually referenced by **_PlatformRegressionTest_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_PlatformRegressionTest_**.

**_org.apache.poi.poifs.crypt.EncryptionVerifier: org.apache.poi.poifs.crypt.EncryptionVerifier clone()_** is invoked by **_PlatformRegressionTest_** via the following path:
<pre><code>
Invocation path------
&lt;com.cognizant.devops.platformregressiontest.test.common.XLUtils: java.lang.String getCellData(java.lang.String,java.lang.String,int,int)&gt; Insights\PlatformRegressionTest\target\classes
&lt;org.apache.poi.xssf.usermodel.XSSFRow: org.apache.poi.xssf.usermodel.XSSFCell getCell(int)&gt; Repositories\org\apache\poi\poi-ooxml\4.1.0\poi-ooxml-4.1.0.jar
&lt;org.apache.poi.xssf.usermodel.XSSFRow: org.apache.poi.xssf.usermodel.XSSFCell getCell(int,org.apache.poi.ss.usermodel.Row$MissingCellPolicy)&gt; Repositories\org\apache\poi\poi-ooxml\4.1.0\poi-ooxml-4.1.0.jar
&lt;org.apache.poi.xssf.usermodel.XSSFRow$1: void clinit()&gt; Repositories\org\apache\poi\poi-ooxml\4.1.0\poi-ooxml-4.1.0.jar
&lt;org.apache.poi.ss.usermodel.CellType: org.apache.poi.ss.usermodel.CellType[] values()&gt; Repositories\org\apache\poi\poi\4.1.2\poi-4.1.2.jar
&lt;org.apache.poi.poifs.crypt.agile.AgileEncryptionVerifier: java.lang.Object clone()&gt; Repositories\org\apache\poi\poi-ooxml\4.1.0\poi-ooxml-4.1.0.jar
&lt;org.apache.poi.poifs.crypt.agile.AgileEncryptionVerifier: org.apache.poi.poifs.crypt.agile.AgileEncryptionVerifier clone()&gt; Repositories\org\apache\poi\poi-ooxml\4.1.0\poi-ooxml-4.1.0.jar
&lt;org.apache.poi.poifs.crypt.EncryptionVerifier: org.apache.poi.poifs.crypt.EncryptionVerifier clone()&gt;
</code></pre>

## Suggested fixing solutions:
1. Upgrade dependency **_org.apache.poi:poi-ooxml_** from **_4.1.0_** to **_4.1.2_**.Because the newer version **_org.apache.poi:poi-ooxml:4.1.2_** does not invoke the above missing methods, such changing cn solve the problem.
2. Change direct dependency **_org.apache.poi:poi_** from **_4.1.2_** to **_4.1.0_**. Because version **_4.1.0_** includes the above missing methods and is compatible with other versions of **_org.apache.poi:poi_** in the project.
This repair will introduce the following new conflicts, but these conflicts are benign (will not cause runtime exceptions).
Conflict: commons-codec:commons-codec versions: [1.12, /1.13, /1.9]

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.cognizant.devops:PlatformRegressionTest:jar:7.6
[INFO] +- <b>org.apache.poi:poi:jar:4.1.2:compile</b>
[INFO] \- org.apache.poi:poi-ooxml:jar:4.1.0:compile
[INFO]    \- <b>(org.apache.poi:poi:jar:4.1.0:compile - omitted for conflict with 4.1.2)</b>
</code></pre>

**Comment by vishwajitmankar** [comment]
Above issues has been closed. Requested to test and reopen if required.
