### ISSUE TITLE
How to collect jenkins data and render graph

### ISSUE THREAD

**Issue by pratapsandy** [CognizantOneDevOps/Insights#3]
hi,

I had installed all the components required for insight application. But am not sure on how to collect the jenkins data and render graph for the same. I tried configuring jenkinsAgent as shown below and running JenkinsAgent() python script , gives me an error
![image](https://user-images.githubusercontent.com/34029891/33301964-f8797bb8-d41e-11e7-9689-f2b916bcfe29.png)
PFB log_jenkinsAgent and config file

[log_JenkinsAgent.log](https://github.com/CognizantOneDevOps/Insights/files/1508467/log_JenkinsAgent.log)

[config.txt](https://github.com/CognizantOneDevOps/Insights/files/1508469/config.txt)

**Comment by vganjare** [comment]
Hi,

The iSight MQ exchange is not defined. Can you follow the instructions as mentioned @ http://platform.cogdevops.com/windows/InSights_V1.0.zip

Download and extract zip. 
Follow the step-by-step instructions from Instructions_V1.0 document.

Also, please validate if the Jenkins REST API is accessible.

Thanks,
Vishal
