### ISSUE TITLE
infra.cogdevops.com not responding

### ISSUE THREAD

**Issue by amenome** [CognizantOneDevOps/Insights#377]
```
$ ping infra.cogdevops.com
PING infra.cogdevops.com (54.166.124.44) 56(84) bytes of data.
...
```

Referenced in Dockerfile:
```
https://infra.cogdevops.com:8443/repository/docroot/insights_install/installationScripts/latest/RHEL/python/get-pip.py
```

1) is this server down permanently?
2) shouldn't we get the latest pip scripts from their original source, rather than from cogdevops.com?

**Comment by gauravdeshmukh612** [comment]
Due to security policy, it is not available on internet, please refer latest script
