### ISSUE TITLE
Data Collection issue in Insight

### ISSUE THREAD

**Issue by roversmanoj** [CognizantOneDevOps/Insights#4]
hi,
I wanted to collect sonar data, configured config.json  and followed below steps for the same

![sonarconf](https://user-images.githubusercontent.com/8178256/33305575-c7304a9e-d434-11e7-9bf9-8a326cad3f80.png)
i see no data is being collected and got an issue 'No json object could be decoded' . PFB config.json and log file. Please help me to resolve this issue
[config.txt](https://github.com/CognizantOneDevOps/Insights/files/1508736/config.txt)
[log_SonarAgent.log](https://github.com/CognizantOneDevOps/Insights/files/1508737/log_SonarAgent.log)

Regards,
Manoj.

**Comment by vganjare** [comment]
Hi Manoj,

The iSight MQ exchange is not defined. Can you follow the instructions as mentioned @ http://platform.cogdevops.com/windows/InSights_V1.0.zip

Download and extract zip. 
Follow the step-by-step instructions from Instructions_V1.0 document.

Also, please validate if the Sonar REST API is accessible.

Thanks,
Vishal

**Comment by SwethaSridhar** [comment]
Hi,
iSightMQ is defined and RabbitMQ is up and running
![image](https://user-images.githubusercontent.com/22519028/33374352-d2c142da-d52b-11e7-8dd6-415b8d2effde.png)
While configuring the SonarAgent, it says 
![image](https://user-images.githubusercontent.com/22519028/33374583-caf31230-d52c-11e7-8b85-5269e71a72ec.png)
But the config.json file does have an attribute 'toolsTimeZone'.
The config.json file is also attached.

[config.txt](https://github.com/CognizantOneDevOps/Insights/files/1513738/config.txt)

**Comment by vganjare** [comment]
Hi,

Can you validate if the config.json is correct? This error is observed if the config.json is not correct json as per python json standards.

Thanks,
Vishal

**Comment by pratapsandy** [comment]
hi Vishal, 

Thanks for the reply. today we are able to run the SonarAgent python script. And in trackingJson(attached below) i could find the sonar projects. What could be next step, to render graphfor sonar data? Also,in which location this sonar data gets persisted?

Still in sonarAgentlog(attached) file i could find warning message containing "NOT_FOUND - no exchange 'iSight' in vhost '/'" on" . Should we ignore this as it is just a warning? Please give us the clear picture on how to generate graph for sonar data?
[tracking.txt](https://github.com/CognizantOneDevOps/Insights/files/1517737/tracking.txt)

[log_SonarAgent.log](https://github.com/CognizantOneDevOps/Insights/files/1517736/log_SonarAgent.log)

Regards,
Manoj.

**Comment by vganjare** [comment]
For agent data to be consumed, you will need to fire following command:
`curl -X POST --user AdminUser:AdminUserPassword --noproxy 127.0.0.1 --data 'category=CODEQUALITY&toolName=SONAR&agentId=1' http://127.0.0.1:8080/PlatformService/admin/toolsConfig/update`

Thanks,
Vishal

**Comment by pratapsandy** [comment]
hi,
I have tried executing the above mentioned curl command as shown
![image](https://user-images.githubusercontent.com/34029891/33482056-4914c208-d6bd-11e7-8043-de4c0bcd0881.png)
I executed the SonarAgent() python script as well.. now am not sure where the data is being populated and what is the next step to generate sonar graph? I have attached Platformservice.log and tomcat.log for your reference

[log.txt](https://github.com/CognizantOneDevOps/Insights/files/1521511/log.txt)
[catalina.2017-12-01.log](https://github.com/CognizantOneDevOps/Insights/files/1521515/catalina.2017-12-01.log)

Regards,
Manoj.

**Comment by vganjare** [comment]
Hi Manoj,

Validate if the config has been updated using following curl call:
`
curl -X GET --user UserName:Password --noproxy 127.0.0.1 http://127.0.0.1:8080/PlatformService/admin/toolsConfig/readAll
`
This should return the JSON with SONAR configuration.
-Compile the InSights source code using: mvn clean install -DskipTests
-From PlatformEngine/target directory, run command: java -jar PlatformEngine.jar
This will add the MQ subscribers. 

In neo4j, validate if the data is indexed using: match (n:DATA) return distinct labels(n), count(n)

Thanks,
Vishal

**Comment by SwethaSridhar** [comment]
Hi,
After following the above mentioned steps,the neo4j is found to have some nodes created.
![image](https://user-images.githubusercontent.com/22519028/33553675-ad0272ce-d91f-11e7-89d3-9658644baa8d.png)
But, no data or graph is populated in grafana.
And, the PlatformService log file in tomcat says 
"Unable to get the User Role for current org.
java.lang.NullPointerException"
I have attached the log file of PlatformService along with this.Please validate it and help in getting the graph for sonar data.

Regards,
Manoj

[log.txt](https://github.com/CognizantOneDevOps/Insights/files/1527090/log.txt)

**Comment by vganjare** [comment]
Hi Manoj,

I hope you had started the PlatformEngine before running the agent. Also, validate in whether the data is added to RabbitMQ CODEQUALITY_SONAR_QUEUE.

Thanks,
Vishal

**Comment by roversmanoj** [comment]
hi Vishal,

Thanks for the solution we are able to view the sonar data in Grafana and in Insight Dasbhboard as well. 

Regards,
Manoj.
