### ISSUE TITLE
Installation scripts still pointing to V1.0

### ISSUE THREAD

**Issue by vaibhavdevops** [CognizantOneDevOps/Insights#62]
I am trying to new installation on new server. It seems that there is a new version of Insights 3.8.1 released, however the installation scripts are still pointing to V1.0 . I checked the confluence as well, but there is no reference on how to get installable for the latest version. Please update the script locations always point to latest release version or atleast update documentation with correct links

**Comment by mayankdevops** [comment]
Hello Vaibhav,

Thanks for feedback. We have updated the scripts and documentation.
Please find the updated links below.

Confluence : https://onedevops.atlassian.net/wiki/spaces/OI/pages/211638/Installation+of+InSights
Linux:https://github.com/CognizantOneDevOps/Insights/blob/master/Deployment/RHEL7/AutoDeploy_RHEL7.sh
Windows:http://platform.cogdevops.com/insights_install/installationScripts/latest/windows/InSights_Windows.zip

Please let us know if you still face any issues.

Thanks,
-Mayank Gangwal

**Comment by vaibhavdevops** [comment]
Thanks Mayank
