### ISSUE TITLE
Tools Configuration is not accessible in wiki

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/Insights#79]
Hi,
I'm trying to access the wiki page on Tools Configuration
https://onedevops.atlassian.net/wiki/spaces/OI/pages/220367/Tools+Configuration
Any alternate guide for tools configuration?

**Comment by mayankdevops** [comment]
Hello,

That page is no more available as we have updated our documentation. Please refer to: https://onedevops.atlassian.net/wiki/spaces/OI/overview

Please scroll down in this page, it has details section wise.

Please let us know if we can assist further.

Thanks,
-Mayank Gangwal

**Comment by smartdevops** [comment]
Thanks for the information.

**Comment by vishwajitmankar** [comment]
Is there more information you need under this issue or we can close it?
