### ISSUE TITLE
Agent Management Tab is missing

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/Insights#83]
Hi,
I have tried to set up Insights with Oracle Linux 7 by following the below link
https://onedevops.atlassian.net/wiki/spaces/OI/pages/211638/Installation+of+InSights
I have completed the setup using insights_all option.
Agent Management Tab is missing in UI. 
Am I using the right jar/binaries file? Please help.
![image](https://user-images.githubusercontent.com/33824782/40464248-b6c4a13a-5f37-11e8-99fb-40afcddc4d46.png)

**Comment by mayankdevops** [comment]
Hello,

We are in process of releasing a major version. You should see the latest release and updated documentation in some time. We will update this ticket once we do that. This release should resolve the discrepancy.

Thanks,
-Mayank Gangwal

**Comment by mayankdevops** [comment]
Hello,

We hope you are able to see the new Tab for Agent management. Please let us know if you still face any issues with this Tab.

Thanks,
-Mayank Gangwal
