### ISSUE TITLE
New agent registration failing due to RabbitMQ queue creation

### ISSUE THREAD

**Issue by SashikalaV** [CognizantOneDevOps/Insights#87]
Registration of New Agent is failing due to issues with Queue creation in RabbitMq

**Comment by vishwajitmankar** [comment]
Issue has been fixed and checked in. Pull request has been accepted for the same.

**Comment by vishwajitmankar** [comment]
Testing in progress.

**Comment by vishwajitmankar** [comment]
Tested, working as expected. Closing the issue.
