### ISSUE TITLE
Tomcat not starting after latest binary deployment

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/Insights#88]
I have updated the latest artifacts PlatformService.war,  InSightsUI.zip & Agent 2.0 configurations.
Tomcat is not starting after the update.  Attaching the logs catalina.out & log.out. 
[catalina.txt](https://github.com/CognizantOneDevOps/Insights/files/2045156/catalina.txt)
[log.txt](https://github.com/CognizantOneDevOps/Insights/files/2045157/log.txt)

**Comment by smartdevops** [comment]
I'm able to login to the insight UI.
Now the landing page shows below error 
![image](https://user-images.githubusercontent.com/33824782/40638654-18a398b6-632a-11e8-96f7-8bce8a137e5e.png)

Dashboard Tab
![image](https://user-images.githubusercontent.com/33824782/40638662-2a41eca8-632a-11e8-9e36-3474a99d5f4d.png)

Please help!

**Comment by vishwajitmankar** [comment]
Hope this issue has been resolved. Can we close this.

**Comment by smartdevops** [comment]
Vishwajit,

This is resolved by using the latest binaries shared by Insight Team. 
Please share the steps to create binaries from the master branch.
