### ISSUE TITLE
Insights 4.1 getCurrentOrgAndRole failing

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/Insights#92]
Environment details:

Insights v1.4
OS: Oracle Linux 7
I have used the scripts from below URL to setup insight
https://github.com/CognizantOneDevOps/Insights/tree/master/Deployment/RHEL7/reference-DocRoot-Scripts

I'm able to log into the UI dashboard with the PowerUser. But the admin tab is not enabled.
PowerUser was configured as Grafana Admin in Grafana.

Attaching the PlatformService logs 
[log.out.txt](https://github.com/CognizantOneDevOps/Insights/files/2066811/log.out.txt)

Please help.

**Comment by vishwajitmankar** [comment]
I hope everything is working as expected. Please let us know whether we can close this ticket.

**Comment by vishwajitmankar** [comment]
Closing this ticket as there are no updates.
