### ISSUE TITLE
Unable to view the admin tab / roles after Insights UI is up.

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#95]
After configuring the Insights application setup using the default scripts, we were unable to view the "Admin" / "Agent Management" tab in the UI. Also, the user roles are not getting populated in the UI.
![insights_github_issue_ui](https://user-images.githubusercontent.com/40206308/41638698-6531842c-7478-11e8-8dd5-eee5bebe20b0.png)

**Comment by vishwajitmankar** [comment]
Could you please share following detail s-
1. Exact OS version
2. Default scripts ran successfully? Do you have the logs.
3. Which insights version, assuming latest 4.1?
4. Verify all components are running like Grafana, PostgreSQL, WAR deployed successfully in tomcat, Neo4j, Elasticsearch.
5. server-config,json having all parameters verified. If running on AWS env, grafanaendpoint should have public ip.

**Comment by gjerin594** [comment]
1. OS Version - Red Hat Enterprise Linux Server release 7.5 (Maipo)
2. All default scripts Ran successfully - Except the insights_python.sh (Path to platformagents.zip gave a 404)
3. Insights Version - 4.1
4. All components verified to be up and running. War file deployment successful.
5. 
server-config.json in Insights home/.Insights updated with all the required values.

**Comment by gjerin594** [comment]
Presently able to view all the tabs in the Insights App. For the benefit of anyone who might face this issue, if you are installing the Application components and the data sources in different machines / if you are installing each of the components one by one, try the following steps:

1. After the installation of each step, please run the source command on both the /etc/environment and /etc/profile.
2. If the script to install all the components together is not used, you might face this issue.
3. The source commands are running inside the respective shells and not in the parent shell, when you run the installation scripts one by one. So the downstream installations would not be able to pick out the necessary environment variables.
4. After running each of the installation scripts, make sure to check if each of the environment variables are exported to the parent shell.
