### ISSUE TITLE
Path in Script for getting the PlatformAgent.zip does not contain the file.

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#96]
The script for downloading the platform agent zip file is pointing to a directory without the zip.

![insights_github_issue_platformagentpath](https://user-images.githubusercontent.com/40206308/41638788-cdd5d3ca-7478-11e8-82ca-9834e93730ff.png)

The path and the directory have been highlighted 

![insights_github_issue_platformagentpath_url](https://user-images.githubusercontent.com/40206308/41638789-ce344b62-7478-11e8-8c7b-7f1e8f5f4748.png)

**Comment by vishwajitmankar** [comment]
This should not fail your installation. We will remove those lines of code in next release.

**Comment by gjerin594** [comment]
Thank you! Could you also give a clear idea so as to how to set up the platform agent? From the documentation it is understood that the platform agent zip file contains scripts for all the mentioned agents. How can we manually set up the agents without the zip?

**Comment by vishwajitmankar** [comment]
Follow the link - https://onedevops.atlassian.net/wiki/spaces/OI/pages/283475977/Agent+Management
Will request you to go through entire document from start to end, atleast once before starting anything. Answer to half of your queries, should get resolved through documentation.

**Comment by gjerin594** [comment]
@vishwajitmankar We had gone through the entire documentation before we began with the setup for Insights. All the installation / setup steps followed were strictly adhering to the documentation.

The page that you have referenced points to agent registration from the UI. But in our installation, the "Agent Management" Tab is not showing up as mentioned in https://github.com/CognizantOneDevOps/Insights/issues/95

I understand from the above comments that the missing binaries from the script will not cause an issue. My query is how then will the python scripts (Agents) for each tool be present in the machine containing the Insights Application if the platformAgent.zip is not made available?

The below steps were followed to setup the agent as per the steps mentioned at https://onedevops.atlassian.net/wiki/spaces/OI/pages/211638/Installation+of+InSights 
| Agents Installation Instructions | Daemon Agent Configuration and Execution

1. Created a folder for the agent daemon and tool agents.

2. Unzipped the agent daemon zip file with the folder structure starting with com/.

3. Changed the config.json as per documentation at 
<installationFolder>/AgentDaemon/com/cognizant/devops/platformagents/agents/agentdaemon/config.json

4. Ran the installdaemonagent.sh with the OS input to run it as a service.

5. Took the zip file for BitBucket from the docroots path for v4.1 - http://platform.cogdevops.com/insights_install/release/v4.1/agents/bitbucket/

6. Updated the config.json for bitbucket at <installationPath>/v4.1/bitbucket/com/cognizant/devops/platformagents/agents/scm/bitbucket/

7.The Agent install section mentions of a server-config.json but the relative or absolute path to it is not mentioned in the Agent installation section of the document. From the Path mentioned in the "Changes in server-config & uiConfig file" section of "Insights Inference" we got a path pointing to "/usr/INSIGHTS_HOME/.InSights/". The mentioned changes for the JSON file were made including addition of the "agentDetails" section in the file.

8. The war file for platform service was deployed. The db update script execution to register the daemon agent was attempted with a response of "No relations found" from postgres.

Please correct if you find any errors in the method followed.

**Comment by gjerin594** [comment]
Closing this issue as the scripts in the latest releases are working fine. Thanks a ton!
